"""Module for defining the path or constants for the App"""
DATASET_FOLDER = r"App/Dataset/BankNote_Authentication.csv"
DATASET_FILENAME = "BankNote_Authentication.csv"
MODEL_SAVE_PATH = r"App/Models"
CLF_PATH = r"App/Models/clf.pkl"
